CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_BLE_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Pointing / Trackball support
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

# Power / RF
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
