# Copyright (c) 2026 EKS Inc.
# Created by Ryu.
# SPDX-License-Identifier: LicenseRef-EKS-NonCommercial-1.0

CONFIG_ZMK_BLE=y

# Trackball (PMW3610)
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_POLL_INTERVAL_MS=15

# Boot-time inner/outer orientation selector on P0.08
CONFIG_MODU_ALT_THUMB_KSCAN=y

# Battery
CONFIG_ZMK_BATTERY_REPORTING=y

# PWM LED breath effect
CONFIG_PWM=y
CONFIG_MODU_LED_BREATH=y
